### ISSUE TITLE
No session functionality

### ISSUE THREAD

**Issue by derlarsen** [CleverbotIO/node-cleverbot.io#3]
When I initialize the bot like so:

```
var cleverbot = require("cleverbot.io"),
bot = new cleverbot(...);
bot.setNick("1234567890");
bot.create(function (err, response) {
  console.log('bot created:', err, response);
});
```

I get the following output `$ bot created: false undefined`. It seems like there is no session created. When I talk to cleverbot the answers don't match the questions and appear to be completely out of context.

Cheers!

EDIT: Please ignore, I made an error on my side. I used my API KEY as the nick name, which didn't work. '1234567890' works fine.
Please consider this closed.

**Comment by dtesler** [comment]
working on it
