### ISSUE TITLE
Some replies are "Error, the reference "" does not exist"

### ISSUE THREAD

**Issue by ErraticFox** [CleverbotIO/node-cleverbot.io#6]
As the title says, sometimes when I send it a message it'll give me that or an actual reply, it's random on this outcome. Why is this?

**Comment by dtesler** [comment]
This is an apparent issue in the 1.0 API that requires you to set a session
name first

**Comment by ErraticFox** [comment]
And how do I set a session? I'm new to javascript and node.

**Comment by dtesler** [comment]
Simply use the .setNick(name) method of the cleverbot instance.
